name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fda68d6d4fd6a0ef67ddea60ef8461b30a16c7a941050bcc5d1b47dd5524d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
