name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07b89cae50a6a271238d5acfbda3a5edd43fd3f44988c497b186b369c0c3b040"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
