name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc58ff82b1a735a0e37479a135e6515e74cfe7ac5b80602ec8c923040a186fd8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
